export default {
    ade: "https://semantic-ui.com/images/avatar/large/ade.jpg",
    chris: "https://semantic-ui.com/images/avatar/large/chris.jpg",
    christian: "https://semantic-ui.com/images/avatar/large/christian.jpg",
    daniel: "https://semantic-ui.com/images/avatar/large/daniel.jpg",
    elliot: "https://semantic-ui.com/images/avatar/large/elliot.jpg",
    helen: "https://semantic-ui.com/images/avatar/large/helen.jpg",
    jenny: "https://semantic-ui.com/images/avatar/large/jenny.jpg",
    joe: "https://semantic-ui.com/images/avatar/large/joe.jpg",
    justen: "https://semantic-ui.com/images/avatar/large/justen.jpg",
    laura: "https://semantic-ui.com/images/avatar/large/laura.jpg",
    matt: "https://semantic-ui.com/images/avatar/large/matt.jpg",
    nan: "https://semantic-ui.com/images/avatar/large/nan.jpg",
    steve: "https://semantic-ui.com/images/avatar/large/steve.jpg",
    stevie: "https://semantic-ui.com/images/avatar/large/stevie.jpg",
    veronika: "https://semantic-ui.com/images/avatar/large/veronika.jpg",

    elyse: "https://semantic-ui.com/images/avatar2/large/elyse.png",
    kristy: "https://semantic-ui.com/images/avatar2/large/kristy.png",
    lena: "https://semantic-ui.com/images/avatar2/large/lena.png",
    lindsay: "https://semantic-ui.com/images/avatar2/large/lindsay.png",
    mark: "https://semantic-ui.com/images/avatar2/large/mark.png",
    matthew: "https://semantic-ui.com/images/avatar2/large/matthew.png",
    molly: "https://semantic-ui.com/images/avatar2/large/molly.png",
    patrick: "https://semantic-ui.com/images/avatar2/large/patrick.png",
    rachel: "https://semantic-ui.com/images/avatar2/large/rachel.png",

    ade_small: "https://semantic-ui.com/images/avatar/small/ade.jpg",
    chris_small: "https://semantic-ui.com/images/avatar/small/chris.jpg",
    christian_small: "https://semantic-ui.com/images/avatar/small/christian.jpg",
    daniel_small: "https://semantic-ui.com/images/avatar/small/daniel.jpg",
    elliot_small: "https://semantic-ui.com/images/avatar/small/elliot.jpg",
    helen_small: "https://semantic-ui.com/images/avatar/small/helen.jpg",
    jenny_small: "https://semantic-ui.com/images/avatar/small/jenny.jpg",
    joe_small: "https://semantic-ui.com/images/avatar/small/joe.jpg",
    justen_small: "https://semantic-ui.com/images/avatar/small/justen.jpg",
    laura_small: "https://semantic-ui.com/images/avatar/small/laura.jpg",
    matt_small: "https://semantic-ui.com/images/avatar/small/matt.jpg",
    nan_small: "https://semantic-ui.com/images/avatar/small/nan.jpg",
    steve_small: "https://semantic-ui.com/images/avatar/small/steve.jpg",
    stevie_small: "https://semantic-ui.com/images/avatar/small/stevie.jpg",
    veronika_small: "https://semantic-ui.com/images/avatar/small/veronika.jpg",

    elyse_small: "https://semantic-ui.com/images/avatar2/small/elyse.png",
    kristy_small: "https://semantic-ui.com/images/avatar2/small/kristy.png",
    lena_small: "https://semantic-ui.com/images/avatar2/small/lena.png",
    lindsay_small: "https://semantic-ui.com/images/avatar2/small/lindsay.png",
    mark_small: "https://semantic-ui.com/images/avatar2/small/mark.png",
    matthew_small: "https://semantic-ui.com/images/avatar2/small/matthew.png",
    molly_small: "https://semantic-ui.com/images/avatar2/small/molly.png",
    patrick_small: "https://semantic-ui.com/images/avatar2/small/patrick.png",
    rachel_small: "https://semantic-ui.com/images/avatar2/small/rachel.png"

}